### PR TITLE
Add support for custom paths

### LINKED ISSUE #18: Path variable support
I saw this was mentioned in #8 and I'd also like to have the ability to set path variables.

I'm implementing a dashaboard for Pingdom and they use the format /api/2.1/summary.performance/{checkid} for requests, which requires a new data source for each checkid currently.

### LINKED ISSUE #23: Template variable chaining is not working
I'm trying to chain template variables and it seems that the variable expansion is not working in the "Custom query parameters" field in template variables. When I set: 
```
search=$filter
```
The query becomes: 
```
/?search=%24filter
```
The same happens with the double-bracket notation. 

In the query editor this is working and only seems to affect the template variable editor.

### PR DESCRIPTION
**Pull request by marcusolsson**
This PR adds support for appending custom paths to the data source URL for each query.

Screen Shot 2020-12-04 at 14 52 17

Closes #18
Closes #23

### CODE REVIEW

**Comment by marcusolsson** [comment]
@Vamic and @oplehto Any thoughts on this before I merge?

**Comment by marcusolsson** [comment]
Forgot about the variable query editor 😅 I'll update it right away

**Comment by Vamic** [comment]
Looks good to me.

**Comment by oplehto** [comment]
Looks great!

**Comment by marcusolsson** [comment]
Thanks for the feedback! Love how this turned out ❤️

**Comment by marcusolsson** [comment]
Available now in [v0.7.0](https://grafana.com/grafana/plugins/marcusolsson-json-datasource?version=0.7.0)! 🎉

**Pull request merged**
