### PR TITLE
Fixes #222 - Added grafana global variables when doing a query using jsonata

### LINKED ISSUE #222: Grafana global variables not working with JSONata
When trying to use one of the grafana default global variables (https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/) such as $__to or $__from there is no result for JSONata but for JSONPath it works as expected.
It also seems like the ${var} notation doesn't work for JSONata.

Working Example:
image

Non Working Example:
image

### PR DESCRIPTION
**Pull request by amng**
I add all the current global variables, couldn't find the list of variables as it seems to be internal to TemplateSrv, so whenever there are new global variables added or old ones removed this list will have to be updated.
Couldn't create unit tests at the moment as there are many things to mock  (so it wouldn't be exactly a unit test anymore).

image

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hey, and thanks for this! Have you tested this whether this works for formatting options like `${__from:date:iso}`? I suspect that we eventually will have to run the entire JSONata query through the templateSrv, but if this works then maybe we can hold out a bit on that decision.

**Comment by amng** [comment]
> Hey, and thanks for this! Have you tested this whether this works for formatting options like `${__from:date:iso}`? I suspect that we eventually will have to run the entire JSONata query through the templateSrv, but if this works then maybe we can hold out a bit on that decision.

Hi, no this fix was really just to add the global variables to JSONata, like what was already being done for the dashboard variables. This means they will work in the same way.
$__to will work however ${__to} will not.
All in all is just converting the grafana global variables into JSONata variables.

**Review by marcusolsson — APPROVED** [review]

**Comment by marcusolsson** [comment]
Thank you! 🙏

**Comment by marcusolsson** [comment]
Available in 1.3.1.

**Pull request merged**
