### PR TITLE
Using JSON.stringify instead of toString for object types in parseValue

### LINKED ISSUE #110: Use `JSON.strignify` to convert objects to string instead of `toString`
### The Problem

It is currently not possible to extract nested objects from the query because the `.toString()` function applied on Javascript objects when parsing values returns `"[object Object]"` which is useless. Using `JSON.stringify()` instead for objects will give us the JSON as string, which can be used and displayed as JSON in grafana.

### Suggested Solution

This line:

https://github.com/marcusolsson/grafana-json-datasource/blob/37b14b5abf420cb93798c98e0eda93ef530fb4d9/src/parseValues.ts#L31

Would become something like:

```js
    return values.every((_) => typeof _ === 'string') ? values : values.map((_) => {
          if(_ === null) return _;
          else if(typeof(_) === 'object') return JSON.strignify(_); // Provides a proper output string for objects
          else return _.toString();
});
```

Note that `typeof(_) === 'object'` will match Objects and Arrays. If you want to avoid matching arrays, use `typeof(_) === 'object' && !Array.isArray(_)`. It mainly depends on which output you prefer for arrays:

```js

console.log([1,2,3].toString());             // Output: '1,2,3'
console.log(JSON.strignify([1,2,3]));        // Output: '[1,2,3]'
```

### PR DESCRIPTION
**Pull request by Totalus**
Fixes #110

### CODE REVIEW

**Comment by marcusolsson** [comment]
This is awesome! There seems to be a few linter issues. Could you take a look?

**Comment by Totalus** [comment]
Yes, so how do I do that ? Because when I build the plugin locally it does not throw any errors.

Do I just need to run prettier on the code ? I tried yesterday, but it did also modify lines that I did not modify in the files, so I got confused.

**Comment by marcusolsson** [comment]
Hm, that is weird. `yarn build` should indeed give you the linter errors locally. Prettier should do the job. When was the last time you ran yarn install? The Grafana team updates the prettier config in pretty much every release, so you want to make sure that you're running the same Grafana dependencies as the CI. Try running `yarn install` and then prettier.

If you don't want to spend the time troubleshooting this, I'd be happy to merge this and fix the linter issues on my end. I created a branch with the correct formatting here in case you want to compare: https://github.com/marcusolsson/grafana-json-datasource/compare/Totalus/main

**Comment by Totalus** [comment]
> When was the last time you ran yarn install? 

5 days ago. I just removed `node_modules`, ran `yarn build` again and it still gives the same result.

```
$ yarn list | grep @grafana
├─ @grafana/data@7.4.3
├─ @grafana/e2e-selectors@7.4.3
│  ├─ @grafana/tsconfig@^1.0.0-rc1       
├─ @grafana/eslint-config@2.1.0
├─ @grafana/runtime@7.4.3
│  ├─ @grafana/data@7.4.3
│  ├─ @grafana/ui@7.4.3
├─ @grafana/slate-react@0.22.9-grafana   
├─ @grafana/toolkit@7.4.3
│  ├─ @grafana/data@7.4.3
│  ├─ @grafana/eslint-config@2.1.0       
│  ├─ @grafana/tsconfig@^1.0.0-rc1       
│  ├─ @grafana/ui@7.4.3
├─ @grafana/tsconfig@1.0.0-rc1
├─ @grafana/ui@7.4.3
│  ├─ @grafana/data@7.4.3
│  ├─ @grafana/e2e-selectors@7.4.3       
│  ├─ @grafana/slate-react@0.22.9-grafana
│  ├─ @grafana/tsconfig@^1.0.0-rc1
```

Seeing anything wrong ?

What command runs for checking linting if not `prettier` ? I could try running the linting manually, try to figure out why it does not work properly. Maybe the linting does not find the config file and falls back to a default config ?

**Comment by marcusolsson** [comment]
Merged and fixed the linter issues in main (https://github.com/marcusolsson/grafana-json-datasource/commit/159f54b003e4f24b52dd9e37215d13207b75058f). Many thanks for helping out here! ❤️

**Pull request merged**
